### ISSUE TITLE
Update to latest release

### ISSUE THREAD

**Issue by adamjstewart** [conda-forge/lightly-feedstock#20]
### Comment:

This feedstock is several releases out of date. In particular, the most recent release does not yet have NumPy 2 support. @guarin can you update to the latest release?

**Comment by guarin** [comment]
Thanks for the ping, will try to sort this out.

**Comment by guarin** [comment]
Updated the feedstock and added two new releases (1.5.10 and 1.5.12). 1.5.12 is the latest available release.
